[[plugins]] # toml highlight
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # status line
repo = 'itchyny/lightline.vim'

[[plugins]] 
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup = 1
'''
