[[plugins]] # TOMLのシンタックスハイライト
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # ステータス行を見やすく
repo = 'itchyny/lightline.vim'

#[[plugins]] # goコマンド補完
#repo = 'fatih/vim-go'
#on_ft = 'go'
#hook_add = '''
#let g:go_highlight_build_constraints = 1
#let g:go_highlight_extra_types = 1
#let g:go_highlight_fields = 1
#let g:go_highlight_functions = 1
#let g:go_highlight_methods = 1
#let g:go_highlight_operators = 1
#let g:go_highlight_structs = 1
#let g:go_highlight_types = 1
#let g:go_fmt_command = "goimports"
#let g:go_metalinter_autosave_enabled = ['vet', 'golint']
#let g:go_metalinter_autosave = 1
#'''
#
#
[[plugins]] # neocomplete
repo = 'Shougo/neocomplete.vim'

[[plugins]] # コード補完
repo = 'Shougo/deoplete.nvim'
# プラグインが dein.vim によって追加されたとき実行
hook_add = '''
let g:deoplete#enable_at_startup = 1
let g:python3_host_prog=$PYENV_ROOT.'/versions/anaconda3-5.3.1/bin/python'
let g:python_host_prog=$PYENV_ROOT.'/versions/anaconda2-5.3.1/bin/python'
'''

#[[plugins]] # コード補完（Golang用）
#repo = 'zchee/deoplete-go'
#on_ft = 'go'
#depends = ['deoplete.nvim']
#hook_source = '''
#    let g:deoplete#sources#go#gocode_binary = $GOPATH . '/bin/gocode'
#'''
#
#
#[[plugins]]
#repo = "davidhalter/jedi-vim"
#on_ft = ['python']
#hook_source = '''
#let g:jedi#auto_vim_configuration = 0
#let g:jedi#popup_select_first     = 0
#let g:jedi#show_call_signatures   = 0 
#'''
#
#
#[[plugins]]
#repo = 'zchee/deoplete-clang'
#on_ft = ['c', 'cpp', 'cmake']
#hook_source = '''
#    let g:deoplete#sources#clang#libclang_path = system("llvm-config --prefix")[:-2] . '/lib/libclang.dylib'
#    let g:deoplete#sources#clang#clang_header = system("llvm-config --prefix")[:-2] . '/lib/clang'
#    let g:deoplete#sources#clang#sort_algo = 'priority'
#    let g:deoplete#sources#clang#clang_complete_database="./build/"
#'''
#depends = ['deoplete.nvim']
#
#[[plugins]]
#repo = 'Shougo/neoinclude.vim'
#on_ft = ['c', 'cpp']
#depends = ['deoplete.nvim']
