name: check dotfile on macos
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: 1.19
  PYTHON_VERSION: 3.9.0

jobs:
  Run-Shell-Files:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3 
    - name: run install.sh and asdf-install.sh
      run: ./install.sh && /bin/zsh ~/.zshrc && /bin/zsh ./asdf-install.sh $GO_VERSION $PYTHON_VERSION
